export type { ChatClient, ChatProviderConfig, ChatClientTools, ToolResultSubmission } from './core/createChatClient';
export { createChatClient } from './core/createChatClient';
export { ChatProvider } from './react/ChatProvider';
export { useChatClient, useChatRuntime } from './core/context';
export { defineChatExtensions, installChatExtension, installChatExtensions, normalizeChatExtensions } from './core/extensions';
export type { ChatExtension, ChatExtensionConfig, ChatRuntimeApi } from './core/extensions';
export { useChatExtensions } from './core/useChatExtensions';
export { createChatStore, useAppDispatch, useAppSelector, selectTimelineEntities, selectOverlay } from './store/store';
export type { ChatStore, RootState, AppDispatch } from './store/store';
export { timelineSlice } from './store/timelineSlice';
export { overlaySlice } from './store/overlaySlice';
export { defineWidget, createWidgetRegistry, ChatWidgetRegistry } from './widgets/widgetRegistry';
export type { WidgetProps, WidgetDefinition, WidgetRegistry } from './widgets/widgetRegistry';
export { useWidget } from './widgets/useWidget';
export { WidgetOutlet } from './widgets/WidgetOutlet';
export { UnknownWidget } from './widgets/UnknownWidget';
export { defineTimelineProjector, createTimelineProjectorRegistry, ChatTimelineProjectorRegistry } from './ws/projectorRegistry';
export type { TimelineProjector, TimelineProjectorContext, TimelineProjectorRegistry, TimelineProjectionResult } from './ws/projectorRegistry';
export type { TimelineMutation } from './ws/timelineEvents';
export { defineTool, defineToolUI, createToolRegistry, ChatToolRegistry } from './tools/toolRegistry';
export type { FrontendTool, HumanTool, BackendToolUI, ToolRegistry, ToolExecutionMode, ToolDefinition } from './tools/toolRegistry';
export { useTool } from './tools/useTool';
export { useFrontendTool } from './tools/useFrontendTool';
export { useHumanTool } from './tools/useHumanTool';
export { useToolUI } from './tools/useToolUI';
export { ToolCallOutlet } from './tools/ToolCallOutlet';
export type { ChatDebugEvent, ChatDebugHandler } from './ws/wsManager';
